version: '3.1'

services:
  react-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bolnica-back_local_network

networks:
  bolnica-back_local_network:
    external: true