// DEMO

export const GET_DEMOS = "GET_DEMOS";
export const GET_DEMO = "GET_DEMO";
export const CREATE_DEMO = "CREATE_DEMO";
export const UPDATE_DEMO = "UPDATE_DEMO";
export const DELETE_DEMO = "DELETE_DEMO";


// APPOINTMENTS

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const CREATE_APPOINTMENT_NURSE = "CREATE_APPOINTMENT_NURSE"
export const DELETE_APPOINTMENT_NURSE = "DELETE_APPOINTMENT_NURSE"

// DOCTORS

export const GET_DOCTORS = "GET_DOCTORS";